### ISSUE TITLE
The msg.Answer's 1st RR maybe CNAME

### ISSUE THREAD

**Issue by AlexanderZhan** [katakonst/go-dns-proxy#1]
https://github.com/katakonst/go-dns-proxy/blob/e7a4e9ef0dc52485d2a171bc80c532a3516cd4cc/dns_proxy.go#L79

proxy.Cache.Set(q.Name, &msg.Answer[len(msg.Answer)-1])

**Comment by katakonst** [comment]
Fixed this on master.
Big Thank You for your time in spoting this!
